### ISSUE TITLE
Scrollbar in settings

### ISSUE THREAD

**Issue by matytyma** [Loudbooks/PasteBook#5]
A horizontal scrollbar is being displayed in settings, although there is noting to scroll through
![image](https://github.com/user-attachments/assets/e208f490-0834-4ce8-a5e4-9e81087bc25b)

**Comment by thesamgordon** [comment]
Cannot reproduce. What browser was this done on?

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/c1202fc6-b783-4e74-9027-356f95d4c39d">

**Comment by matytyma** [comment]
Vivaldi. Seems it's related just to that browser, Firefox and GNOME Epiphany are unaffected
